// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type crashtrackerCrashEvent struct {
	_            structs.HostLayout
	EventType    uint8
	Pad          [3]uint8
	Sig          uint32
	SigCode      uint32
	_            [4]byte
	SigAddr      uint64
	Pid          uint32
	Tid          uint32
	Uid          uint32
	Gid          uint32
	Comm         [16]int8
	KtimeNs      uint64
	BoottimeNs   uint64
	Ip           uint64
	Sp           uint64
	UserStackLen uint32
	KernStackLen uint32
	UserStack    [128]uint64
	KernStack    [128]uint64
	CgroupId     uint64
	PidNsId      uint32
	_            [4]byte
}

// loadCrashtracker returns the embedded CollectionSpec for crashtracker.
func loadCrashtracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CrashtrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load crashtracker: %w", err)
	}

	return spec, err
}

// loadCrashtrackerObjects loads crashtracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*crashtrackerObjects
//	*crashtrackerPrograms
//	*crashtrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCrashtrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCrashtracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// crashtrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type crashtrackerSpecs struct {
	crashtrackerProgramSpecs
	crashtrackerMapSpecs
	crashtrackerVariableSpecs
}

// crashtrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type crashtrackerProgramSpecs struct {
	TracepointOomMarkVictim         *ebpf.ProgramSpec `ebpf:"tracepoint__oom__mark_victim"`
	TracepointSchedSchedProcessExit *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSignalSignalDeliver   *ebpf.ProgramSpec `ebpf:"tracepoint__signal__signal_deliver"`
}

// crashtrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type crashtrackerMapSpecs struct {
	CrashEvents    *ebpf.MapSpec `ebpf:"crash_events"`
	PendingCrashes *ebpf.MapSpec `ebpf:"pending_crashes"`
	RateLimit      *ebpf.MapSpec `ebpf:"rate_limit"`
}

// crashtrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type crashtrackerVariableSpecs struct {
	UnusedCrashEvent *ebpf.VariableSpec `ebpf:"__unused_crash_event"`
}

// crashtrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCrashtrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type crashtrackerObjects struct {
	crashtrackerPrograms
	crashtrackerMaps
	crashtrackerVariables
}

func (o *crashtrackerObjects) Close() error {
	return _CrashtrackerClose(
		&o.crashtrackerPrograms,
		&o.crashtrackerMaps,
	)
}

// crashtrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCrashtrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type crashtrackerMaps struct {
	CrashEvents    *ebpf.Map `ebpf:"crash_events"`
	PendingCrashes *ebpf.Map `ebpf:"pending_crashes"`
	RateLimit      *ebpf.Map `ebpf:"rate_limit"`
}

func (m *crashtrackerMaps) Close() error {
	return _CrashtrackerClose(
		m.CrashEvents,
		m.PendingCrashes,
		m.RateLimit,
	)
}

// crashtrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCrashtrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type crashtrackerVariables struct {
	UnusedCrashEvent *ebpf.Variable `ebpf:"__unused_crash_event"`
}

// crashtrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCrashtrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type crashtrackerPrograms struct {
	TracepointOomMarkVictim         *ebpf.Program `ebpf:"tracepoint__oom__mark_victim"`
	TracepointSchedSchedProcessExit *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSignalSignalDeliver   *ebpf.Program `ebpf:"tracepoint__signal__signal_deliver"`
}

func (p *crashtrackerPrograms) Close() error {
	return _CrashtrackerClose(
		p.TracepointOomMarkVictim,
		p.TracepointSchedSchedProcessExit,
		p.TracepointSignalSignalDeliver,
	)
}

func _CrashtrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed crashtracker_bpfel.o
var _CrashtrackerBytes []byte
