version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      GitHub Actions:
        applies-to: version-updates

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/docker"
    schedule:
      interval: "daily"