version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
<<<<<<< HEAD
=======

  - package-ecosystem: pip
    directory: /_integration-tests/utils/agent
    schedule:
      interval: daily
>>>>>>> 3b149a3 (Prepare repository for opensourcing)
