stages:
  - deploy
  - internal_image_deploy

variables:
  DOWNSTREAM_BRANCH:
    value: "master"
    description: "Run a specific datadog-reliability-env branch downstream"
  IMAGES_DOWNSTREAM_BRANCH:
    value: "master"
    description: "Run a specific images branch downstream"

deploy_to_reliability_env:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: manual
      allow_failure: true
  trigger:
    project: DataDog/apm-reliability/datadog-reliability-env
    branch: $DOWNSTREAM_BRANCH
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PROJECT_NAME: $CI_PROJECT_NAME
    UPSTREAM_COMMIT_SHA: $CI_COMMIT_SHA

prepare_release_tag:
  stage: internal_image_deploy
  tags: ["arch:amd64"]
  rules:
    - if: $CI_COMMIT_TAG =~ /^gitlab-v\d+\.\d+\.\d+(-rc\d+)?$/
      when: on_success
  script:
    - echo "Preparing release tag"
    - echo "RELEASE_TAG=${CI_COMMIT_TAG#gitlab-v}" > .env
    - if [[ "$RELEASE_TAG" == *-rc* ]]; then
    -   echo "RELEASE_PROD=false" >> .env
    - else
    -   echo "RELEASE_PROD=true" >> .env
    - fi
  artifacts:
    reports:
      dotenv: .env
  needs:

publish_internal_container_image:
  stage: internal_image_deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^gitlab-v\d+\.\d+\.\d+(-rc\d+)?$/
      when: on_success
  trigger:
    project: DataDog/images
    branch: $IMAGES_DOWNSTREAM_BRANCH
  variables:
    IMAGE_VERSION: tmpl-v1
    IMAGE_NAME: dd-otel-host-profiler
    RELEASE_TAG: $RELEASE_TAG
    RELEASE_PROD: $RELEASE_PROD
    RELEASE_STAGING: true
  needs:
    - prepare_release_tag
