version: "2"
linters:
  default: all
  disable:
    # Disabled because of
    #   - too many non-sensical warnings
    #   - not relevant for us
    #   - false positives
    #
    - cyclop
    - depguard
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - protogetter
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115 # integer overflow, too many false positives
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        printf: # analyzer name, run `go tool vet help` to see all analyzers
          funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
            - debug,debugf,debugln
            - error,errorf,errorln
            - fatal,fatalf,fataln
            - info,infof,infoln
            - log,logf,logln
            - warn,warnf,warnln
            - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
    misspell:
      locale: US
      ignore-rules:
        - rela
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/DataDog/dd-otel-host-profiler
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
