run:
  timeout: 10m
  
linters:
  enable-all: true
  disable:
    # Disabled because of
    #   - too many non-sensical warnings
    #   - not relevant for us
    #   - false positives
    #
    - cyclop
    - depguard
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox # complains about TODO etc
    - gofumpt
    - gomnd
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - protogetter
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wsl
    - wrapcheck
    # the following linters are deprecated
    - execinquery
    - exportloopref

linters-settings:
  goimports:
    local-prefixes: github.com/DataDog/dd-otel-host-profiler
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - debug,debugf,debugln
          - error,errorf,errorln
          - fatal,fatalf,fataln
          - info,infof,infoln
          - log,logf,logln
          - warn,warnf,warnln
          - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
  misspell:
    locale: US
    ignore-words:
      - rela
  gosec:
    excludes:
      - G115 # integer overflow, too many false positives
