name: Labeled

on:
  pull_request:
    types: [labeled]

jobs:
  build-release:
    if: ${{ github.event.label.name == 'publish-dev-test' }}
    name: Build
    uses: ./.github/workflows/pre-release.yaml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
